## 1. Loading Libraries ----
print("1")
suppressMessages(source("./load_libraries.R"))
load("./process.RData")

print("All Files Loaded")

## NEW. Loading all Shiny Modules ----
source("./Shiny_Modules/dashboard_sidebar.R")
source("./Shiny_Modules/notification_menu.R")
source("./Shiny_Modules/message_menu.R")
source("./Shiny_Modules/task_menu.R")
source("./Shiny_Modules/top_metrics_valuebox.R")
source("./Shiny_Modules/trf_1a_traffic_channel.R")
source("./Shiny_Modules/trf_1b_traffic_source.R")
source("./Shiny_Modules/trf_1c_traffic_segmentdevice.R")
source("./Shiny_Modules/trf_1d_traffic_segmenttier.R")
source("./Shiny_Modules/trf_1f_traffic_tier.R")
source("./Shiny_Modules/trf_2a_traffic_daily.R")
source("./Shiny_Modules/trf_2b_traffic_cumulative_daily.R")

source("./Shiny_Modules/direct_traffic_city_filter.R")
source("./Shiny_Modules/trf_3a_direct_traffic_city.R")
source("./Shiny_Modules/trf_3b_direct_traffic_percentage_city.R")
source("./Shiny_Modules/trf_3c_direct_traffic_listing_profile.R")
source("./Shiny_Modules/trf_3d_direct_traffic_growth.R")

source("./Shiny_Modules/tra_1a_transactions_mode.R")
source("./Shiny_Modules/tra_1b_transactions_monetizeable_unique.R")
source("./Shiny_Modules/tra_1c_transactions_source.R")
source("./Shiny_Modules/tra_1d_transactions_segment.R")
source("./Shiny_Modules/tra_1g_transactions_tier.R")
source("./Shiny_Modules/tra_2a_transactions_daily_cumulative.R")
source("./Shiny_Modules/tra_2b_transactions_daily.R")
source("./Shiny_Modules/tra_3a_abs_cancel_country.R")
source("./Shiny_Modules/cnv_1a_conversion_nonunique_old.R")
source("./Shiny_Modules/cnv_1b_conversion_unique_new.R")
source("./Shiny_Modules/cnv_1c_conversion_tier.R")
source("./Shiny_Modules/cnv_1d_conversion_unique_source.R")
source("./Shiny_Modules/cnv_2a_conversion_daily.R")

source("./Shiny_Modules/cpt_0a_cpt_weekly_summary.R")
source("./Shiny_Modules/cpt_0b_cpt_weekly_summary.R")
source("./Shiny_Modules/cpt_0c_cpt_monthly_expansion.R")
source("./Shiny_Modules/cpt_1a_transactions_to_enterprise.R")
source("./Shiny_Modules/cpt_1b_transactions_monetised_bu.R")
source("./Shiny_Modules/cpt_1c_transactions_monetised_funnels.R")

source("./Shiny_Modules/cpt_2a_mrr_reach_cpt.R")
source("./Shiny_Modules/cpt_2b_ecpt_reach_cpt.R")
source("./Shiny_Modules/cpt_2c_ecpt_credit_transactions.R")

source("./Shiny_Modules/cpt_3a_live_practices.R")
source("./Shiny_Modules/cpt_3b_live_doctors.R")
source("./Shiny_Modules/cpt_3c_docs_20_recos.R")
source("./Shiny_Modules/cpt_3d_docs_10_reviews.R")
source("./Shiny_Modules/cpt_3e_docs_with_book.R")

source("./Shiny_Modules/cpt_4a_cpt_practice_churn_90d.R")
source("./Shiny_Modules/cpt_4b_cpt_practice_churn_30d.R")
source("./Shiny_Modules/cpt_4c_cpt_practice_acquisition.R")

source("./Shiny_Modules/gmv_1a_gmv_overall.R")
source("./Shiny_Modules/gmv_1b_vpe_overall.R")
source("./Shiny_Modules/liq_1a_liquidity.R")

source("./Shiny_Modules/csv_download.R")
print("10")
